http:
  routers:
    allbackendRouter:
      rule: "Host(`localhost`)"
      service: allbackend

  services:
    allbackend:
      loadBalancer:
        servers:
          - url: 'http://localhost:1111/'
          - url: 'http://localhost:2222/'
          - url: 'http://localhost:3333/'
          - url: 'http://localhost:4444/'
